/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.emptool;

public class ConsoleHost {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new ConsoleHost().getGreeting());
        System.out.println("[PROGRAM START]");

        System.out.println("[PROGRAM END]");
        
    }
}
