/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.emptool;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
import javax.swing.*;

import com.emptool.ui.MiniAppDesktop;

import java.awt.*;
import java.awt.event.*;

public class ConsoleHost {

    private static final org.apache.logging.log4j.Logger log = LogManager.getLogger(ConsoleHost.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //Console console = System.console();
        // System.out.println(new ConsoleHost().getGreeting());

        //System.out.println("[PROGRAM START]");
        
        log.info("[PROGRAM START]");

        // Print demo log messges
        log.trace("the built-in TRACE level");  // intLevel 600
        log.debug("the built-in DEBUG level");  // intLevel 500
        log.info("the built-in INFO level");    // intLevel 400
        log.warn("the built-in WARN level");    // intLevel 300
        log.error("the built-in ERROR level");  // intLevel 200
        log.fatal("the built-in FATAL level");  // intLevel 100

        // Start of application
        //SimpleExample fr = new SimpleExample();

        // JFrame f=new JFrame();//creating instance of JFrame  
        // JButton b=new JButton("click");//creating instance of JButton  
        // b.setBounds(130,100,100, 40);//x axis, y axis, width, height  
        // f.add(b);//adding button in JFrame  
        // f.setSize(400,500);//400 width and 500 height  
        // f.setLayout(null);//using no layout managers  
        // f.setVisible(true);//making the frame visible


        // ImageIcon icon = createImageIcon("images/middle.gif");
        // JLabel label1 = new JLabel("Image and Text", icon, JLabel.CENTER);

        try {
            UIManager.setLookAndFeel(
                UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception e) { }
        JFrame.setDefaultLookAndFeelDecorated(true);

        MiniAppDesktop desktopApp = new MiniAppDesktop();

        //1. Create the frame.
        // JFrame frame = new JFrame("FrameDemo");
        // JLabel label2 = new JLabel("Text-Only Label");

        // JMenuBar menuBar;
        // JMenu menu, submenu;
        // JMenuItem i1, i2, i3, i4, i5;  

        // menuBar = new JMenuBar();

        // menu=new JMenu("Menu");  
        // submenu=new JMenu("Sub Menu");  
        // i1=new JMenuItem("Item 1");  
        // i2=new JMenuItem("Item 2");  
        // i3=new JMenuItem("Item 3");  
        // i4=new JMenuItem("Item 4");  
        // i5=new JMenuItem("Item 5");  
        // menu.add(i1);
        // menu.add(i2);
        // menu.addSeparator();
        // menu.add(i3);  
        // submenu.add(i4); 
        // submenu.add(i5);  
        // menu.add(submenu);  

        //Build the first menu.
        // menu = new JMenu("A Menu");
        // menu.setMnemonic(KeyEvent.VK_A);
        // menu.getAccessibleContext().setAccessibleDescription("The only menu in this program that has menu items");
        // menuBar.add(menu);
        
        // menuBar.add(menu);


        // frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // frame.getContentPane().add(label2, BorderLayout.CENTER);
        // frame.setJMenuBar(menuBar);
        
        // frame.setLayout(null);  

        // //frame.pack();
        // frame.setSize(400,400);
        // frame.setVisible(true);


        // Frame f=new Frame();  
        // Button b=new Button("click me");  
        // b.setBounds(30,50,80,30);  
        // f.add(b);  
        // f.setSize(300,300);  
        // f.setLayout(null);  
        // f.setVisible(true);  


        // Frame fr=new Frame();       
        // Label lb = new Label("UserId: "); 
        // fr.add(lb);           
        // TextField t = new TextField();
        // fr.add(t);
        // fr.setSize(500, 300);  
        // fr.setLayout(new FlowLayout());
        // fr.setVisible(true);


        log.info("[PROGRAM END]");

        //System.out.println("[PROGRAM END]");

        // try {
        //     BufferedReader reader =
        //         new BufferedReader(new InputStreamReader(System.in));
        //     String name = reader.readLine();
        //     System.out.println(name);  
        // } catch (Exception ex) {
        //     //TODO: handle exception
        //     ex.printStackTrace(); // if any error occurs
        // }


        // try {
        //     System.out.println("1");
        //     Console console = System.console();

        //     if (console == null) {
        //         System.out.println("No console; terminating...");
        //     }

        //     if (console != null) {
        //         System.out.println("2");
        //        String name = console.readLine("Name: ");
        //        System.out.println("Name entered : " + name);
        //     }     

        //     System.out.println("3");

        //  } catch(Exception ex) {
        //     ex.printStackTrace(); // if any error occurs
        //  }

        // System.out.println("[PROGRAM END]");
        //console.readLine("AS");
        //String x = console.readLine("AS");
    }
}

