/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.emptool;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        ConsoleHost classUnderTest = new ConsoleHost();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
