/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import app.Connect;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import static java.lang.System.out;

import swing_app.HelloSwingApp;

public class App {

    private static final Logger logger = LogManager.getLogger(App.class);

    public String getGreeting() {
        return "Hello world.";
    }

    static void PrintTestMessages() {
        logger.fatal("Sample FATAL test message");
        logger.error("Sample ERROR test message");
        logger.warn( "Sample WARN  test message");
        logger.info( "Sample INFO  test message");
        logger.debug("Sample DEBUG test message");
        logger.trace("Sample TRACE test message");
    }

    public static void main(String[] args) {

        out.println("[START PROGRAM]");

        // PrintTestMessages();

        HelloSwingApp app = new HelloSwingApp();

        app.Run();

        //System.out.println(new App().getGreeting());

        // app.Connect.connect();

        // logger.info("{}", () -> "sad");

        out.println("[END PROGRAM]");
        
    }
}
